$(file >$(outdir)/Makefile-am.0.mk,$(_am.pass0))
include $(outdir)/Makefile-am.0.mk
$(file >$(outdir)/Makefile-am.1.mk,$(_am.pass1))
include $(outdir)/Makefile-am.1.mk
$(file >$(outdir)/Makefile-am.2.mk,$(_am.pass2))
include $(outdir)/Makefile-am.2.mk
$(file >$(outdir)/Makefile-am.3.mk,$(_am.pass3))
include $(outdir)/Makefile-am.3.mk
$(file >$(outdir)/Makefile-am.4.mk,$(_am.pass4))
include $(outdir)/Makefile-am.4.mk
$(file >$(outdir)/Makefile-am.5.mk,$(_am.pass5))
include $(outdir)/Makefile-am.5.mk
