PACKAGE = systemd
VERSION = 229
PACKAGE_NAME = systemd
PACKAGE_TARNAME = systemd
PACKAGE_VERSION = 229
PACKAGE_STRING = systemd 229
PACKAGE_BUGREPORT = http://github.com/systemd/systemd/issues
PACKAGE_URL = http://www.freedesktop.org/wiki/Software/systemd

ACLOCAL = ${SHELL} /home/luke/src/parabola/systemd/build-aux/missing aclocal-1.15
AUTOCONF = ${SHELL} /home/luke/src/parabola/systemd/build-aux/missing autoconf
AUTOHEADER = ${SHELL} /home/luke/src/parabola/systemd/build-aux/missing autoheader
AUTOMAKE = ${SHELL} /home/luke/src/parabola/systemd/build-aux/missing automake-1.15
CPP = gcc -E
CPPFLAGS = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
FGREP = /usr/bin/grep -F# Requires AC_PROG_FGREP
GPERF = gperf
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LIBTOOL = $(SHELL) $(top_builddir)/libtool
M4 = /usr/bin/m4
M4_DEFINES =  -DHAVE_SECCOMP -DHAVE_SELINUX -DHAVE_APPARMOR -DHAVE_PAM -DHAVE_ACL -DHAVE_SMACK -DHAVE_MICROHTTPD -DHAVE_LIBCURL -DHAVE_LIBIDN -DHAVE_LIBIPTC -DENABLE_TIMESYNCD -DENABLE_COREDUMP -DENABLE_RESOLVED -DENABLE_NETWORKD -DENABLE_KDBUS -DHAVE_SYSV_COMPAT
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p# Requires AC_PROG_MKDIR_P
MSGFMT = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
NM = gcc-nm
NMEDIT = 
OBJCOPY = objcopy
OBJDUMP = objdump
STRINGS = strings
STRIP = strip
XGETTEXT = /usr/bin/xgettext

INSTALL_SCRIPT = ${INSTALL}# Requires AC_PROG_INSTALL
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
