#!/usr/bin/env bash

# The reason we do `find`/`while read`-loops instead of `find -exec` commands
# is that we want errors from the inner loop to bubble up.

fixup_makefiles() (
	find -type f -name Makefile | while read -r filename; do
		sed -r -i "s|(/\.\.)*/config.mk|/$(realpath -ms --relative-to="${filename%/*}" config.mk)|" "$filename"
	done
)

fixup_includes() (
        find $(find . -type d -name include) -type d | while read -r dir; do
                lib="${dir##*/}"
                pushd "$dir" >/dev/null
                find . -type f -exec sed -ri -e "s|$lib/||" -- {} +
                popd >/dev/null
        done

        find src \( -name '*.h' -o -name '*.c' \) -type f | while read -r filename; do
                "$0"--includes "$filename"
        done
)

main() {
        set -e
        set -o pipefail
        fixup_makefiles
        fixup_includes
}

main "$@"
